# Use an official Node.js runtime as a parent image
FROM node:16.17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# COPY ./presDB.sql /docker-entrypoint-initdb.d/

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# RUN npm rebuild bcrypt --build-from-source

# Expose the port on which the app runs
EXPOSE 3030

# Define the command to run your backend
CMD ["npm", "start"]
